services:
  - type: web
    name: json-server-persist
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: |
      if [ ! -f /data/db.json ]; then
        cp ./db-init.json /data/db.json
      fi
      node index.js
    disks:
      - name: json-db-disk
        mountPath: /data
        sizeGB: 1
